root = "."
tmp_dir = ".tmp"

[build]
  pre_cmd = ["templ generate"]
  cmd = "go build -o ./.tmp/main ./cmd/"
  bin = "./.tmp/main"
  delay = 10
  exclude_dir = [ ".tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "scss", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true


[proxy]
  app_port = 8080
  enabled = true
  proxy_port = 8090

[misc]
  clean_on_exit = true
